# Generated by Django 4.0 on 2021-12-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_photo_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
